### ISSUE TITLE
Nodejs 8.x is required, not 6.x

### ISSUE THREAD

**Issue by tomballgithub** [JennerPalacios/SimpleSpoofNinja#1]
The directions say to install nodejs but when you go to the link provided it says 6.x is the latest.  The 'install from a package' page has options for both 6.x and 8.x.  

Discord.js requires nodejs 8.X.  Please make it clear on the instructions to use 8.x.

**Comment by tomballgithub** [comment]
I would also go ahead and add these notes from discord.js since this does not install clean.  

Node.js 8.0.0 or newer is required.
Ignore any warnings about unmet peer dependencies, as they're all optional.

**Comment by tomballgithub** [comment]
From the instructions, shouldn't this says 'servers.json' and not 'config.json'?

Join all the spoofing servers using the invite codes in config.json

**Comment by JennerPalacios** [comment]
Thank you! guide has been updated...   ❤️   👍 🥇
