### ISSUE TITLE
Bot cant kick or ban after checking

### ISSUE THREAD

**Issue by ghost** [JennerPalacios/SimpleSpoofNinja#2]
Hi, need your help, the bot cant kick or ban after checking spoofers servers.

i have this error during a process

(node:4194) UnhandledPromiseRejectionWarning: TypeError: spoofServersFoundAgain.includes is not a function
    at Timeout._onTimeout (/user/SimpleSpoofNinja/SpoofNinja.js:1560:40)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

Forget something?

Thanks

**Comment by JennerPalacios** [comment]
Fixed!
The moderator bot was using the dummy account's collection, but since the dummy account is no longer required in one's personal server, it was returning this error - a blank return or no property, error.
