### ISSUE TITLE
dont see spoof member

### ISSUE THREAD

**Issue by ghost** [JennerPalacios/SimpleSpoofNinja#3]
Hey , for you info since a last discord's update.. The bot cant see other spoof member in discord listed :/
He see only Him.. I think Discord has pah this jail

**Comment by ghost** [comment]
i have a same issue. the bot has not worked since the last Discord update. Ninja only sees himself.

**Comment by JennerPalacios** [comment]
[Jan 25th 2020] R.I.P
Discord’s update included blinding userBots/selfBots; they stopped them from executing certain functions/calls such as fetchAllMembers, <guild>.fetchMembers(), <guild>.fetchMember(), <selfBot>.on(“guildMemberAdd”) (onJoin detection), etc et
